package org.solcorp.etech

public enum PermissionType {
	PERMISSION_CAN_VIEW_PROJECT(1, "canViewProject"),
	PERMISSION_CAN_VIEW_ACTUAL_RATE(2, "canViewActualRate"),
	PERMISSION_CAN_VIEW_STANDARD_COST(3, "canViewStandardCost"),
	PERMISSION_CAN_MODIFY_STANDARD_COST(4, "canModifyStandardCost"),
	PERMISSION_CAN_VIEW_PRICING(5, "canViewPricing"),
	PERMISSION_CAN_PERFORM_TIMESHEET_ENTRY(6, "canPerformTimesheetEntry"),
	PERMISSION_CAN_MODIFY_TIMESHEET_ENTRY(7, "canModifyTimesheetEntry"),
	PERMISSION_CAN_APPROVE_TIME(8, "canApproveTime"),
	PERMISSION_CAN_PERFORM_ACCOUNTING_PERIOD_MAINTENANCE(9, "canPerformAccountingPeriodMaintenance"),
	PERMISSION_CAN_VIEW_PROJECT_REPORTS(10, "canViewProjectReports"),
	PERMISSION_CAN_VIEW_EMPLOYEE_REPORTS(11, "canViewEmployeeReports"),
	PERMISSION_CAN_VIEW_COE_REPORTS(12, "canViewCOEReports"),
	PERMISSION_CAN_VIEW_DEPARTMENT_REPORTS(13, "canViewDepartmentReports"),
	PERMISSION_CAN_VIEW_CLIENT_REPORTS(14, "canViewClientReports"),
	PERMISSION_CAN_SUBMIT_PROJECT(15, "canSubmitProject"),
	PERMISSION_CAN_APPROVE_PROJECT(16, "canApproveProject")
	
	private final String value
	private final Integer id

	PermissionType(Integer id, String value) {
		this.id = id
		this.value = value
	}
	
	public int getKey() {
		return id
	}

	public String getValue() {
		return value
	}
	
	
	static permissionList() {
		return [PERMISSION_CAN_VIEW_PROJECT, PERMISSION_CAN_VIEW_ACTUAL_RATE, 
		PERMISSION_CAN_VIEW_STANDARD_COST, PERMISSION_CAN_MODIFY_STANDARD_COST, PERMISSION_CAN_VIEW_PRICING, PERMISSION_CAN_PERFORM_TIMESHEET_ENTRY, 
		PERMISSION_CAN_MODIFY_TIMESHEET_ENTRY, PERMISSION_CAN_APPROVE_TIME, PERMISSION_CAN_PERFORM_ACCOUNTING_PERIOD_MAINTENANCE, PERMISSION_CAN_VIEW_PROJECT_REPORTS, 
		PERMISSION_CAN_VIEW_EMPLOYEE_REPORTS, PERMISSION_CAN_VIEW_COE_REPORTS, PERMISSION_CAN_VIEW_DEPARTMENT_REPORTS, PERMISSION_CAN_VIEW_CLIENT_REPORTS, 
		PERMISSION_CAN_SUBMIT_PROJECT, PERMISSION_CAN_APPROVE_PROJECT]
	}
	
	public String toString() {
		return this.getValue()
	}
}
