DROP DATABASE if exists etech_dev;
DROP DATABASE if exists etech_test;
DROP DATABASE if exists etech_prod;

CREATE SCHEMA IF NOT EXISTS etech_dev CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALTER,CREATE,SELECT,INSERT,UPDATE,DELETE,EXECUTE ON etech_dev.* TO etech@localhost IDENTIFIED BY 'n6d45UNVM3kN7SpULFeY2tnD';

CREATE SCHEMA IF NOT EXISTS etech_test CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALTER,CREATE,SELECT,INSERT,UPDATE,DELETE,EXECUTE ON etech_test.* TO etech@localhost IDENTIFIED BY 'n6d45UNVM3kN7SpULFeY2tnD';

CREATE SCHEMA IF NOT EXISTS etech_prod CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALTER,CREATE,SELECT,INSERT,UPDATE,DELETE,EXECUTE ON etech_prod.* TO etech@localhost IDENTIFIED BY 'n6d45UNVM3kN7SpULFeY2tnD';